[global]
# Your Spotify account name.
username = "21bwsvzap5i6jtibdbhruhhiq"

# Your Spotify account password.
password = "carsareawesomeyay"
backend = "alsa" # use portaudio for macOS [homebrew]
device = "default"  # omit for macOS
mixer = "PCM"  # omit for macOS
volume_controller = "alsa"  # use softvol for macOS
device_name = "ArchLinux"
# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 320
cache_path = "/home/seabert/.cache/spotifyd"
volume_normalisation = true
normalisation_pregain = -10
#device_type = "computer"
