#!/bin/sh

pgrep -x sxhdk > /dev/null || sxhkd &

if [ -x ~/open_monitor.sh ]; then
	source ~/open_monitor.sh
fi

xsetroot -cursor_name left_ptr
#xmodmap ~/.Xmodmap
ibus-daemon -drx
#clight &
picom &
~/.fehbg &
xrdb ~/.Xresources
lxpolkit &
udiskie &
thunar --daemon &
~/Naga_KeypadMapper/nagastart.sh &
fcitx5 &
xdotool behave_screen_edge --delay 300 --quiesce 300 top exec "$HOME/hideBar.sh" &
dunst &
clipmenud &
#~/./hideIt.sh --name 'polybar-mybar_DP-3' -p 3 -d top -H &
#xdo raise -a 'polybar-mybar_DP-3' &

num_monitors="$(xrandr --query | grep ' connected ' | wc -l)"
monitor_name="$(xrandr --query | grep ' connected ')"
IN_MON=${monitor_name:0:4}
EX_MON="DP-1-2"
#if [ $num_monitors -eq 1 ]; then
	##for d in I II III IV V; do
		##bspc desktop -r $d 2>&1 /dev/null || true
	##done
	#bspc monitor "$IN_MON" -d 一 二 三 四 五 六 七 八 九 十
#else
	##bspc monitor DP-3 -d I II III IV V
	##bspc monitor DP-2 -d VI VII VIII IX X
	##bspc monitor DP-3 -d I II III IV V VI VII VIII IX X
	#bspc monitor "$EX_MON" -d 一 二 三 四 五 六 七 八 九 十
#fi


bspc config border-width       2
bspc config window-gap         4

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config top_padding 0
#bspc config ignore_ewmh_struts true

bspc config external_rules_command "$HOME/bspwm-rule"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^7'
#bspc rule -a "Picture in picture" state=floating
#bspc rule -a Spotify state=floating
bspc rule -a feh state=floating
bspc rule -a anki state=floating

bspc config normal_border_color "#1F1F28"
bspc config active_border_color "#D27E99"
bspc config focused_border_color "#FF5D62"
bspc config presel_feedback_color "#727169"

bspc config focus_follows_pointer true

# first startup
if [[ "$1" = 0 ]]; then
	if [[ $(xrandr -q | grep "${EX_MON} connected") ]]; then
		#xrandr --output "$EX_MON" --mode 2560x1440 --pos 0x0 --primary --rate 59.95 --x-prop-non_desktop 0 --output "$IN_MON" --mode 1920x1080 --pos 0x0 --rate 60.01
		#bspc monitor "$EX_MON" -d 一 二 三 四 五 六 七 八 九
		#bspc monitor "$IN_MON" -d 十
		#bspc wm -O "$EX_MON" "$IN_MON"
		bspc monitor "$EX_MON" -d 一 二 三 四 五 六 七 八 九 十
		~/.config/polybar/launch-ext.sh &
	else
		bspc monitor "$IN_MON" -d 一 二 三 四 五 六 七 八 九 十
		~/.config/polybar/launch.sh &
	fi
fi

monitor_plugged() {
	bspc monitor "$IN_MON" -a Desktop
	# move all desktops to external monitor
	for desktop in $(bspc query -D -m "$IN_MON"); do
		bspc desktop "$desktop" --to-monitor "$EX_MON"
	done
	#bspc monitor "$EX_MON" -o 一 二 三 四 五 六 七 八 九 十
	# remove default desktop
	bspc desktop Desktop --remove
	# refresh
	bspc monitor "$EX_MON" -o 一 二 三 四 五 六 七 八 九 十
	#bspc wm -O "$EX_MON" "$IN_MON"
}
monitor_unplugged() {
	bspc monitor "$EX_MON" -a Desktop
	for desktop in $(bspc query -D -m "$EX_MON"); do
		bspc desktop "$desktop" --to-monitor "$IN_MON"
	done

	# delete default desktops
	bspc desktop Desktop --remove

	bspc monitor "$IN_MON" -o 一 二 三 四 五 六 七 八 九 十
}

if [[ $(xrandr -q | grep "${EX_MON} connected") ]]; then
  # set xrandr rules for docked setup
  #xrandr --output "$IN_MON" --mode 1920x1080 --pos 0x0 --rotate normal --output "$EX_MON" --primary --mode 2560x1440 --pos 0x0 --rotate normal
	xrandr --output "$IN_MON" --mode 1920x1080 --pos 0x0 --rate 60.01 --output "$EX_MON" --primary --mode 2560x1440 --pos 0x0 --rate 59.95 --rotate normal
	~/.config/polybar/launch-ext.sh &
	if [[ $(bspc query -D -m "${EX_MON}" | wc -l) -ne 10 ]]; then
    monitor_plugged
  fi

  bspc wm -O "$EX_MON" "$IN_MON"
else
  # set xrandr rules for mobile setup
  #xrandr --output "$IN_MON" --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1-2 --off
	xrandr --output "$IN_MON" --mode 1920x1080 --pos 0x0 --primary --rate 60.01 --output "$EX_MON" --off
	~/.config/polybar/launch.sh &
  if [[ $(bspc query -D -m "${IN_MON}" | wc -l) -ne 10 ]]; then
    monitor_unplugged
  fi
fi

