#!/bin/sh

pgrep -x sxhdk > /dev/null || sxhkd &

if [ -x ~/open_monitor.sh ]; then
	source ~/open_monitor.sh
fi

xsetroot -cursor_name left_ptr
xmodmap ~/.Xmodmap
ibus-daemon -drx
#clight &
picom &
~/.fehbg &
xrdb ~/.Xresources
lxpolkit &
udiskie &
thunar --daemon &
~/.config/polybar/launch.sh &
~/Naga_KeypadMapper/nagastart.sh &
fcitx5 &

num_monitors="$(xrandr --query | grep 'connected' | wc -l)"
if [ $num_monitors -eq 1 ]; then
	for d in I II III IV V; do
		bspc desktop -r $d 2>&1 /dev/null || true
	done
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
else
	bspc monitor DP-1-2 -d I II III IV V
	bspc monitor eDP1 -d VI VII VIII IX X
fi

bspc config border-width       2
bspc config window-gap         12

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config top_padding 0

bspc config external_rules_command "$HOME/bspwm-rule"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord state=floating follow=on
#bspc rule -a "Picture in picture" state=floating
#bspc rule -a Spotify state=floating
bspc rule -a feh state=floating
bspc rule -a anki state=floating

bspc config normal_border_color "#1F1F28"
bspc config active_border_color "#D27E99"
bspc config focused_border_color "#FF5D62"
bspc config presel_feedback_color "#727169"

bspc config focus_follows_pointer true
