#! /bin/sh

pgrep -x sxhdk > /dev/null || sxhkd &

xmodmap ~/.Xmodmap
picom &
lxpolkit &
thunar --daemon &
udiskie &
~/.fehbg &

if [ -x $HOME/open_monitor.sh ]; then
	open_monitor.sh
fi

num_monitors="$(xrandr --query | grep 'connected' | wc -l)"
if [ $num_monitors -eq 1 ]; then
	for d in I II III IV V; do
		bspc desktop -r $d 2>&1 /dev/null || true
	done
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
else
	bspc monitor DP-1-2 -d I II III IV V
	bspc monitor eDP1 -d VI VII VIII IX X
fi

bspc config border-width       2
bspc config window-gap         12

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord state=floating
bspc rule -a feh state=floating
bspc rule -a anki state=floating

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

