set -as terminal-features ",foot:RGB"
set -s escape-time 0

set -g default-command "${SHELL}"

set -g mouse on

setw -g monitor-activity on
set -g visual-activity on

# apparently nicer copy?
# y and p as in vim
bind Escape copy-mode
unbind p
bind p paste-buffer
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection

set -g mode-keys vi
set -g history-limit 30000

set -g status off

# enable yazi peviews
set -gq allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# who needs a mouse
set -g mouse off
# bind-key m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"
#correct timezone
# set -g status-right '#(TZ="Pacific/Vancouver" date +%%H:%%M:%%S)'

# open new panes in current directory
bind b split-window -h -p 35 -c '#{pane_current_path}'
bind v split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

#list windows with " like screen
bind '"' choose-window
unbind w

# moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
